quarkus.http.port=8082

quarkus.rest-client.api-externa.url=${API_EXTERNA_URL:https://economia.awesomeapi.com.br}
quarkus.rest-client.api-externa.connect-timeout=${API_EXTERNA_CONNECT_TIMEOUT:3000}
quarkus.rest-client.api-externa.read-timeout=${API_EXTERNA_READ_TIMEOUT:5000}

quarkus.cache.caffeine."cotacao-externa".expire-after-write=PT15M
